service: ask-allegra

frameworkVersion: ">=1.4.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs4.3
  profile: default
  memorySize: 128

functions:
  getLatestNews:
    handler: handler.getLatestNews
    events:
      - alexaSkill
